### ISSUE TITLE
일기 목록에 이미지 생성 전 일기가 표시되지 않는 건

### ISSUE THREAD

**Issue by BambooKim** [GrimUriCapstone/web#1]
일기 목록에 후보 이미지 생성 완료가 안 된 일기는 표시되지 않는 것 같은데

이미지 생성 중 표시라도 해 놓는 것이 좋지 않을까요~?

**Comment by gene-ss** [comment]
후보 이미지 선택 전에 노출 안되게 했습니다.

**Comment by BambooKim** [comment]
그럼 사용자는 일기 작성 직후 ~ 이미지 생성 알림 전 사이에는 자신이 쓴 일기를 확인도 못하고, 제대로 작성이 됐는지 볼 수도 없는데
ui적으로 개선이 필요하지 않을까 생각이 드네요

**Comment by gene-ss** [comment]
해결 필요
