### ISSUE TITLE
[기능] 클라이언트 명시적 로그아웃 시 API 호출

### ISSUE THREAD

**Issue by BambooKim** [GrimUriCapstone/web#4]
# 클라이언트 명시적 로그아웃
## 필요성
* [https://github.com/GrimUriCapstone/backend/issues/44](url)
### 동작
1. 로그아웃 버튼 클릭
2. 클릭 시 해당 기기의 FCM Token 정보를 Request Body에 담아 API 호출
3. 서버는 해당 FCM Token 정보를 삭제.
### Request Body
``` json
{
  "fcm_token": "string"
}
```

**Comment by gene-ss** [comment]
배포 완료
